plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.5'
	id 'io.spring.dependency-management' version '1.1.6' // ACTUALIZADO: Versión del plugin
}

group = 'com.celotts'
version = '0.0.1'

java {
	sourceCompatibility = '21'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.postgresql:postgresql'
	implementation 'org.springframework.boot:spring-boot-starter-actuator' // AÑADIDO: Spring Boot Actuator
	
	// DevTools: Reinicio automático al detectar cambios
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	
	// Lombok: Para eliminar código repetitivo (Getters, Setters, etc.)
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
